logLevel: "WARNING"
hostname: lsst-lsp-int.ncsa.illinois.edu
# Include leading forward slash in basePath
basePath: /transfer-ingest-monitor
image:
  repository: lsstdm/transfer-ingest-monitor
  tag: v13
  imagePullPolicy: IfNotPresent
monitorNumDays: 2
summaryNumDays: 7
db:
  host: lsst-pg-prod1.ncsa.illinois.edu
  port: 5432
  name: lsstdb1
  user: svclsstdb1ro
# If dev mode is enabled, a static TIM deployment is included for remote debugging and code development
devMode: false
syncthing:
  disabled: false
cronjob:
  schedule: "*/30 * * * *"

data_sources:
- name: "auxtel_ccs"
  type: "ccs"
  data_dir: "/lsstdata/offline/instrument/LATISS-ccs"
  consolidated_db:
    gen3:
      files_table: "obs_auxtel_ccs_files"
      file_events_tables:
      - "obs_auxtel_ccs_gen3_file_events"
    gen2:
      files_table: "obs_auxtel_ccs_files"
      file_events_tables:
      - "obs_auxtel_ccs_gen2_file_events"
  efd:
    host: ldf_stable_efd
    table: 'lsst.sal.ATCamera.logevent_endReadout'
- name: "comcam_ccs"
  type: "ccs"
  data_dir: "/lsstdata/offline/instrument/LSSTComCam-ccs"
  consolidated_db:
    gen3:
      files_table: "obs_comcam_ccs_files"
      file_events_tables:
      - "obs_comcam_ccs_c_gen3_file_events"
      - "obs_comcam_ccs_o_gen3_file_events"
    gen2:
      files_table: "obs_comcam_ccs_files"
      file_events_tables:
      - "obs_comcam_ccs_gen2_file_events"
  efd:
    host: ldf_stable_efd
    table: 'lsst.sal.CCCamera.logevent_endReadout'
- name: "auxtel_arc"
  type: "arc"
  data_dir: "/lsstdata/offline/instrument/LATISS"
  consolidated_db:
    gen3:
      files_table: "obs_auxtel_arc_files"
      file_events_tables:
      - "obs_latiss_arc_gen3_file_events"
    gen2:
      files_table: "obs_auxtel_arc_files"
      file_events_tables:
      - "obs_auxtel_arc_gen2_file_events"
  efd:
    host: ldf_stable_efd
    table: 'lsst.sal.ATArchiver.logevent_imageRetrievalForArchiving'
- name: "comcam_arc"
  type: "arc"
  data_dir: "/lsstdata/offline/instrument/LSSTComCam"
  consolidated_db:
    gen3:
      files_table: "obs_comcam_arc_files"
      file_events_tables:
      - "obs_comcam_arc_gen3_file_events"
    gen2:
      files_table: "obs_comcam_arc_files"
      file_events_tables:
      - "obs_comcam_arc_gen2_file_events"
  efd:
    host: ldf_stable_efd
    table: 'lsst.sal.CCArchiver.logevent_imageRetrievalForArchiving'
- name: "nts_comcam"
  type: "arc"
  data_dir: "/lsstdata/offline/teststand/NCSA_comcam"
  consolidated_db:
    gen3:
      files_table: "nts_comcam_files"
      file_events_tables:
      - "nts_comcam_gen3_file_events"
    gen2:
      files_table: "nts_comcam_files"
      file_events_tables:
      - "nts_comcam_gen2_file_events"
  efd:
    host: ncsa_teststand_efd
    table: 'lsst.sal.CCArchiver.logevent_imageRetrievalForArchiving'
- name: "nts_auxtel"
  type: "arc"
  data_dir: "/lsstdata/offline/teststand/NCSA_auxTel"
  consolidated_db:
    gen3:
      files_table: "nts_auxtel_files"
      file_events_tables:
      - "nts_auxtel_gen3_file_events"
    gen2:
      files_table: "nts_auxtel_files"
      file_events_tables:
      - "nts_auxtel_gen2_file_events"
  efd:
    host: ncsa_teststand_efd
    table: 'lsst.sal.ATArchiver.logevent_imageRetrievalForArchiving'
# - name: "bot"
#   data_dir: "/lsstdata/offline/instrument/LSSTCam-bot"
#   files_table: "slac_bot_files"
#   file_events_tables:
#   - "slac_bot_gen3_file_events"
#   efd:
#     table: ""
#     columns: []
