logLevel: "WARNING"
hostname: lsst-lsp-int.ncsa.illinois.edu
# Include leading forward slash in basePath
basePath: /transfer-ingest-monitor
image:
  repository: lsstdm/transfer-ingest-monitor
  tag: v6
  imagePullPolicy: IfNotPresent
monitorNumDays: 10
db:
  host: lsst-pg-prod1.ncsa.illinois.edu
  port: 5432
  name: lsstdb1
  user: svclsstdb1ro
# If dev mode is enabled, a static TIM deployment is included for remote debugging and code development
devMode: false
cronjob:
  schedule: "*/5 * * * *"
  
data_sources:
- name: "auxtel_ccs"
  data_dir: "/lsstdata/offline/instrument/LATISS-ccs"
  consolidated_db:
    files_table: "obs_auxtel_ccs_files"
    file_events_table: "obs_auxtel_ccs_gen3_file_events"
  efd:
    host: ldf_stable_efd
    tables:
      archiver: 'lsst.sal.ATArchiver.logevent_imageRetrievalForArchiving'
      camera: 'lsst.sal.ATCamera.logevent_endReadout'
  filename:
    raft_separator: '_'
    sensor_separator: '_'
- name: "comcam_ccs"
  data_dir: "/lsstdata/offline/instrument/LSSTComCam-ccs"
  consolidated_db:
    files_table: "obs_comcam_ccs_files"
    # Note that this breaks the pattern with `o_gen3_file_events` instead of `gen3_file_events`
    file_events_table: "obs_comcam_ccs_o_gen3_file_events"
  efd:
    host: ldf_stable_efd
    tables:
      archiver: 'lsst.sal.CCArchiver.logevent_imageRetrievalForArchiving'
      camera: 'lsst.sal.CCCamera.logevent_endReadout'
  filename:
    raft_separator: '_'
    sensor_separator: '_'
- name: "auxtel_arc"
  data_dir: "/lsstdata/offline/instrument/LATISS"
  consolidated_db:
    files_table: "obs_auxtel_arc_files"
    file_events_table: "obs_auxtel_arc_gen3_file_events"
  efd:
    host: ldf_stable_efd
    tables:
      archiver: 'lsst.sal.ATArchiver.logevent_imageRetrievalForArchiving'
      camera: 'lsst.sal.ATCamera.logevent_endReadout'
  filename:
    raft_separator: '_'
    sensor_separator: '_'
- name: "comcam_arc"
  data_dir: "/lsstdata/offline/instrument/LSSTComCam"
  consolidated_db:
    files_table: "obs_comcam_arc_files"
    file_events_table: "obs_comcam_arc_gen3_file_events"
  efd:
    host: ldf_stable_efd
    tables:
      archiver: 'lsst.sal.CCArchiver.logevent_imageRetrievalForArchiving'
      camera: 'lsst.sal.CCCamera.logevent_endReadout'
  filename:
    raft_separator: '_'
    sensor_separator: '_'
- name: "nts_comcam"
  data_dir: "/lsstdata/offline/teststand/NCSA_comcam"
  consolidated_db:
    files_table: "nts_comcam_files"
    file_events_table: "nts_comcam_gen3_file_events"
  efd:
    host: ncsa_teststand_efd
    tables:
      archiver: 'lsst.sal.CCArchiver.logevent_imageRetrievalForArchiving'
      camera: 'lsst.sal.CCCamera.logevent_endReadout'
  filename:
    raft_separator: '-'
    sensor_separator: ''
- name: "nts_auxtel"
  data_dir: "/lsstdata/offline/teststand/NCSA_auxTel"
  consolidated_db:
    files_table: "nts_auxtel_files"
    file_events_table: "nts_auxtel_gen3_file_events"
  efd:
    host: ncsa_teststand_efd
    tables:
      archiver: 'lsst.sal.ATArchiver.logevent_imageRetrievalForArchiving'
      camera: 'lsst.sal.ATCamera.logevent_endReadout'
  filename:
    raft_separator: '-'
    sensor_separator: ''
# - name: "bot"
#   data_dir: "/lsstdata/offline/instrument/LSSTCam-bot"
#   files_table: "slac_bot_files"
#   file_events_table: "slac_bot_gen3_file_events"
#   efd:
#     table: ""
#     columns: []
