hostname: lsst-lsp-int.ncsa.illinois.edu
# Include leading forward slash in basePath
basePath: /transfer-ingest-monitor
image:
  repository: lsstdm/transfer-ingest-monitor
  tag: v2
monitorNumDays: 10
db:
  host: lsst-pg-prod1.ncsa.illinois.edu
  port: 5432
  name: lsstdb1
  user: svclsstdb1ro
# If dev mode is enabled, a static TIM deployment is included for remote debugging and code development
devMode: false
cronjob:
  schedule: "*/5 * * * *"
