---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: {{ .Values.basePath }}
        pathType: Prefix
        backend:
          serviceName: {{ .Release.Name }}-service
          servicePort: 80
