# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: transfer-ingest-monitor
# spec:
#   rules:
#   - host: {{ .Values.hostname }}
#     http:
#       paths:
#       - path: {{ .Values.basePath }}
#         pathType: Prefix
#         backend:
#           service:
#             name: transfer-ingest-monitor
#             port: 
#               number: 80
