---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-nginx
  ports:
  - port: 80
    protocol: TCP
    targetPort: {{ .Values.port | default 80 }}
