---
apiVersion: v1
kind: Service
metadata:
  name: transfer-ingest-monitor
spec:
  selector:
    app: transfer-ingest-monitor-nginx
  ports:
  - port: 80
    protocol: TCP
    targetPort: {{ .Values.port | default 80 }}
