{{ if .Values.devMode }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-debugger
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-debugger
  serviceName: "debugger"
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-debugger
    spec:
      containers:
      - name: debugger
        image: postgres:latest
        command:
        - /bin/bash
        - -c
        - sleep 1000d
{{ end }}
